import { Toaster } from '@/components/ui/sonner';
import '@/styles/globals.css';
import '@/styles/styles.scss';
import { TRPCReactProvider } from '@/trpc/react';
import { type Metadata } from 'next';
import { Lexend_Deca } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Robot Mutasi',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const font = Lexend_Deca({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
});
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={font.className}
    >
      <body>
        <TRPCReactProvider>
          {children}
          <Toaster />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
