import {
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  CodeXml,
  Eye,
  EyeOff,
  FileChartColumn,
  FileDown,
  Landmark,
  LayoutDashboard,
  Link,
  Link2,
  Newspaper,
  Settings,
  Shuffle,
  SquareArrowOutUpRight,
  Trash,
  User,
  Webhook,
  X,
  type LucideIcon,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  x: X,
  fileChart: FileChartColumn,
  landmark: Landmark,
  layoutDashboard: LayoutDashboard,
  newspaper: Newspaper,
  settings: Settings,
  webhook: Webhook,
  code: CodeXml,
  fileDown: FileDown,
  trash: Trash,
  shuffle: Shuffle,
  squareArrowOutUpRight: SquareArrowOutUpRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsDown: ChevronsDown,
  chevronsUp: ChevronsUp,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  link: Link,
  link2: Link2,
  user: User,
  eye: Eye,
  eyeOff: EyeOff,
};
